### PR TITLE
Redirect docs to new Apache URL

### PR DESCRIPTION
**Pull request by patricklucas**

### CODE REVIEW

**Comment by patricklucas** [comment]
Turns out there's a [way to get Netlify to do redirects](https://docs.netlify.com/routing/redirects/) but ¯\_(ツ)_/¯

**Comment by patricklucas** [comment]
Turns out there's a [way to get Netlify to do redirects](https://docs.netlify.com/routing/redirects/) but ¯\\_(ツ)_/¯

**Comment by patricklucas** [comment]
Turns out there's a [way to get Netlify to do redirects](https://docs.netlify.com/routing/redirects/) but ¯\\_(ツ)\_/¯

**Comment by tzulitai** [comment]
Thanks! LGTM, merging ...

**Pull request closed without merging**
